---
title: "Research"
---


My research focuses on heterogeneity within group politics, with broader interests in
race and ethnicity, migration, and discrimination. Primarily, my research focuses on the United States
and Africa. My dissertation explores both of these interests by conducting an in-depth case study
of Eritrean immigrants to uncover how home country socialization towards politics and
identity matter for incorporation in the United States. Other work of mine explores how identity (race, religion, nativity)
matter political attitude formation, candidate evaluations, and political bhevaior.

## Current Projects

### Borders Beyond Borders: Migration, Identity, and the Transnational Political Behavior of the Eritrean Diaspora

**Status:** Dissertation Project

This project explores how the process of identity formation and political socialization is shaped through transnational processes that first begin in 
migrants country of origin. Using  mixed-methods design, I conduct an in-depth study of Eritrean immigrants in the US. Focusing on a relatively new country (1991) that is uniquely positioned between the Arab and African world, this dissertation project illustrates how the processes of identity formation, political learning and attitude formation for Eritrean immigrants is not simply defined by shared racial identity, but rather by salient historical events and transnational considerations. This project bridges theories of the race and ethnicity and politics in American and Comparative politics, as well as other disciplines, to explore how Eritreans draw on historical memory and contemporary experiences to create a multi-faceted identity that is transmitted across the diaspora. Chapters of my dissertation further explore migration and socialization in Eritrea and the US by using interview, archival, survey, and ethnographic methods to understand how the ethnic and national attachment of Eritreans influence political learning/mobilization post migration. The multi-method approach allows for exploration of how political cleavages from Eritrea translate from home country to diasporic community (and vice versa) and how salient political events in the home country anchor a transnational political consciousness and identity. Futher, this work builds and tests my framework of ethnoracialization to further theorize the diversity of political experiences and identities that underpin the categories of “Black immigrants” or “African immigrants”. 



---

### Black and Migrant: Theorizing New Approaches to the Study of Black Immigrants inthe United States

**Status:** Job Market Paper

In recent decades, the fastest-growing number of Black immigrants in the US come from the African continent. Conventional political science research often treats the category of “Black immigrants”  as if it is a settled, stagnant group, often obscuring its meaningful heterogeneity. The study of Black politics in the United States has been anchored by theories that have been informed by and acknowledge the historical treatment of Black people and the pervading importance of race in their daily lives and politics. Yet, the extant literature on Black immigrants often remains focused on aggregation, paying less attention to the country of origin context, or unpacking the many political histories that Black migrants bring with them to the US. To conceptualize the different socialization towards politics and identity in the Black diaspora, I formulate a theory of ethnoracialization to account for the way those who are both Black and migrant experience processes of ethnic and racial hierarchy in the United States and in their home countries. Ultimately, using data from the 2020 CMPS, I show that the process of ethnoracialization manifests differently for African and Afro-Caribbean immigrants and can lead to different outcomes in identity formation and political behavior. 

PDF available upon request.

---

## Research Interests

- Race and Ethnicity
- Immigration 
- Identity
- Political Behavior
- Comparative Politics

